name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/docs-ci
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Generate documentation
      run: |
        doxygen Doxyfile
        
    - name: List generated files
      run: |
        echo "Generated documentation structure:"
        ls -la docs/html/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/html

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/docs-ci'
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4